[package]
name = "tokioticker"
version = "0.0.0"
edition = "2024"
workspace = "./.."
publish = false

[dependencies]
tokio = { version = "1.48.0", features = ["time", "default", "rt-multi-thread", "macros"] }
rand = "0.8"
log = "0.4.29"
