[package]
name = "pastebin"
version = "0.0.0"
edition = "2024"
workspace = "./.."
publish = false

[dependencies]
rocket = "0.5.1"
rand = "0.8"

# FIXME: looks like rocket currently doesnt work with rust 1.80+
[patch.crates-io]
time = { git = "https://github.com/time-rs/time" }
